name: Update pre-commit hooks

on:
  schedule:
    - cron: 0 7 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vrslev/pre-commit-autoupdate@v1.0.0
      - uses: peter-evans/create-pull-request@v3
        with:
          branch: pre-commit-autoupdate
          title: "Update pre-commit hooks"
          commit-message: "Update pre-commit hooks"
          body: Update pre-commit hooks
          labels: dependencies
          delete-branch: True
